### ISSUE TITLE
TLS accesses SIGSEGV on x86_64 macOS on current Cranelift main

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustc_codegen_cranelift#1474]
Update in https://github.com/rust-lang/rustc_codegen_cranelift/commit/1b009aa23844eb618d692bae9762690bd9a6ee47

Crash log at https://github.com/rust-lang/rustc_codegen_cranelift/actions/runs/8497530040/job/23282240626

Only reproduces with the classic linker (pass `-ld_classic` if you use XCode 15, without it works just fine.

Crashes at

```
mini_core_hello_world`mini_core_hello_world::test_tls::hf0b77c2e3ca71442:
    0x1000028bc <+0>:   pushq  %rbp
    0x1000028bd <+1>:   movq   %rsp, %rbp
    0x1000028c0 <+4>:   subq   $0x20, %rsp
    0x1000028c4 <+8>:   leaq   0x5741(%rip), %rdi        ; mini_core_hello_world::TLS::h3c257645134f94e9 + 4
->  0x1000028cb <+15>:  callq  *(%rdi)
    0x1000028cd <+17>:  movzbq (%rax), %r11
```

where `mini_core_hello_world::TLS::h3c257645134f94e9 + 4` should have been `mini_core_hello_world::TLS::h3c257645134f94e9`.

Cranelift's recent update of the object crate seems suspect, but the relocations shown by `llvm-objdump --reloc` seem to be identical.

**Comment by bjorn3** [comment]
Thanks @alexcrichton for helping me reproduce this on their mac.

**Comment by bjorn3** [comment]
`bad.o`:

```
    2acc: 48 8b 3d 04 00 00 00          movq    4(%rip), %rdi           ## 0x2ad7 <__ZN21mini_core_hello_world8test_tls17hf0b77c2e3ca71442E+0x13>
                0000000000002acf:  X86_64_RELOC_TLV     __ZN21mini_core_hello_world3TLS17h3c257645134f94e9E@TLVP
```

`good.o`:

```
    2acc: 48 8b 3d 00 00 00 00          movq    (%rip), %rdi            ## 0x2ad3 <__ZN21mini_core_hello_world8test_tls17hf0b77c2e3ca71442E+0xf>
                0000000000002acf:  X86_64_RELOC_TLV     __ZN21mini_core_hello_world3TLS17h3c257645134f94e9E@TLVP
```

**Comment by philipc** [comment]
The design is:
- in `object::read`, addends are always relative to the place of the relocation, so that consumers can know exactly which symbol+offset is the logical target of the relocation without needing to understand individual relocation types
- `object::write` needs to match `object::read`

Previously this wasn't being done correctly, and I tried to fix this in https://github.com/gimli-rs/object/commit/17c4103093aec15d56c2eecbed358df296894790. Looking at that I think this change will affect all x86/x86-64 relocations that previously used `RelocationKind::MachO` and were pc-relative.

I'm not 100% sure about the semantics of `X86_64_RELOC_TLV`, but I think this change is correct for it, and that line in cranelift should be removed.

**Comment by bjorn3** [comment]
Cranelift fix has been merged.
